### ISSUE TITLE
Using "Source" for WSYWIG editor doesn't save correctly

### ISSUE THREAD

**Issue by willphdavies** [grasshopper-cms/grasshopper-admin#40]
create a rich text field in a content type, create a content item and try to use the "source" option for the editor

http://screencast.com/t/JjqpifxH

**Comment by Duder-onomy** [comment]
This is probably true. CK-Editor is janky. 

The line that propagates the value back to the parent 'content' model is here: https://github.com/Solid-Interactive/grasshopper-admin/blob/master/app/plugins/richtext/view.js#L62

To debug this, I would throw a breakpoint in there, see if it is getting called in your specific scenario. 
Another thing you can do, is implement a beforeSave hook method on this plugin and call that method referenced above when that hook is fired. 

That would look like

```javascript
define([...],
    function (...) {

        'use strict';

        return PluginBaseView.extend({
            afterRender : afterRender,
            remove : remove,
            sortStart : sortStart,
            stopSort : stopSort,
             beforeSave : beforeSave
        })
            .extend(itemSelectModal);

       ....

        function _setEditorEventHandling() {
            this.ckeditor.on('change', _setContentValue.bind(this));
        }

        function _setContentValue() {
            this.model.set('value', this.ckeditor.getData());
        }

        function beforeSave() {
            // Optionally return a promise. 
            _setContentValue.call(this);
        }

        ....
    });
```

**Comment by lukechinworth** [comment]
Added your beforeSave hook suggestion @Duder-onomy
