### ISSUE TITLE
grasshopper fly - failed installing admin

### ISSUE THREAD

**Issue by Jehu** [grasshopper-cms/grasshopper-admin#47]
node v6.3.0

<pre>
Building grasshopper-admin. Please wait, this can take a few minutes. ･･･●･exec error: Error: Command failed: /Users/marco/Programmierung/node/grasshopper/test/node_modules/.bin/grasshopper build
bower contextjs#*                                           invalid-meta for:/var/folders/3s/8b9ykjsn3h10_92mxnvx7kt40000gp/T/marco/bower/ae69027d30342cb2fa72e08c02cc227b-78167-opDeRM/bower.json
bower contextjs#*                                           invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower SparkMD5#*                                            invalid-meta for:/var/folders/3s/8b9ykjsn3h10_92mxnvx7kt40000gp/T/marco/bower/78d00e710581a3a6aea4f00a933ab0f7-78167-HKe5J4/bower.json
bower SparkMD5#*                                            invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower jquery-placeholder#~2.0.7                                 mismatch Version declared in the json (2.0.8) is different than the resolved one (2.0.9)
bower ckeditor#4.3.5                                               retry Download of https://github.com/ckeditor/ckeditor-releases/archive/4.3.5.tar.gz failed with ETIMEDOUT, retrying in 1.7s
bower ace#1.1.3                                                  ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/ajaxorg/ace.git", exit code of #128 fatal: unable to access 'https://github.com/ajaxorg/ace.git/': Failed to connect to github.com port 443: Operation timed out

Additional error details:
fatal: unable to access 'https://github.com/ajaxorg/ace.git/': Failed to connect to github.com port 443: Operation timed out
</pre>

**Comment by pajtai** [comment]
This looks like a connectivity issue based on `fatal: unable to access 'https://github.com/ajaxorg/ace.git/': Failed to connect to github.com port 443: Operation timed out`

**Comment by Jehu** [comment]
@pajtai you're right. seems it was a temporary problem. thanks.
