### ISSUE TITLE
Only first save after loading content view works on embedded type fields

### ISSUE THREAD

**Issue by lukechinworth** [grasshopper-cms/grasshopper-admin#48]
Reproduced on several implementations of admin, so it must be a lib bug.

* Open a piece of content and update several fields; try a standard text field and an embedded type field. 
* Save content. 
* Update the fields again and save again. 
* Refresh the page. 

Notice the text field is up to date, but the embedded field has the value it had after the first save.

**Comment by pajtai** [comment]
Here is the saving as a bb model

https://github.com/grasshopper-cms/grasshopper-admin/blob/master/app/views/contentDetail/contentDetailView.js#L95

and here is the embedded content plugin... maybe there is an issue with the proxy values or some sort of data link issue
https://github.com/grasshopper-cms/grasshopper-admin/blob/master/app/plugins/embeddedtype/view.js#L60

**Comment by lukechinworth** [comment]
`options` were not getting passed through to the grasshopperModel save method.

added here:
https://github.com/grasshopper-cms/grasshopper-admin/blob/master/app/views/contentDetail/contentDetailViewModel.js#L56
